# Generated by Django 5.2 on 2025-04-22 13:42

from django.db import migrations

def create_products(apps, schema_editor):
    Product = apps.get_model('orders', 'Product')
    
    # Create 3 products
    Product.objects.create(
        name="Product 1",
        price=50.00
    )
    Product.objects.create(
        name="Product 2",
        price=75.00
    )
    Product.objects.create(
        name="Product 3",
        price=100.00
    )

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem'),  # Adjust this if the previous migration is different
    ]

    operations = [
        migrations.RunPython(create_products),  # This will run the create_products function
    ]
